version: '3'

services:
  frontend:
    container_name: artexplore-frontend
    build: ./frontend
    restart: always
    networks:
      - back-tier
    ports:
      - "8080:8080"

  backend:
    container_name: artexplore-backend
    build: ./backend
    restart: always
    networks:
      - back-tier
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=${DATABASE_HOST}
    ports:
      - "3000:3000"

  mariadb:
    image: mariadb:latest
    container_name: artexplore-mariadb
    restart: always
    networks:
      - back-tier
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_DATABASE=${DATABASE_NAME}
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/01.sql
      - db-data:/var/lib/mysql

volumes:
  db-data:

networks:
  back-tier:
    driver: bridge